version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root